"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pagination_object import PaginationObject


class TestPaginationObject(unittest.TestCase):
    """PaginationObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginationObject(self):
        """Test PaginationObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginationObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
