"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payer_id import PayerId


class TestPayerId(unittest.TestCase):
    """PayerId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayerId(self):
        """Test PayerId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayerId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
