"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payer_id import PayerId
globals()['PayerId'] = PayerId
from openapi_client.model.create_payment_request_from_id import CreatePaymentRequestFromId


class TestCreatePaymentRequestFromId(unittest.TestCase):
    """CreatePaymentRequestFromId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePaymentRequestFromId(self):
        """Test CreatePaymentRequestFromId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePaymentRequestFromId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
