"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.categories_api import CategoriesApi  # noqa: E501


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_categories_get(self):
        """Test case for categories_get

        Retrieve a paginated list of Categories by query parameter(s)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
