"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_details import PaymentDetails
globals()['PaymentDetails'] = PaymentDetails
from openapi_client.model.patch_payment_intent_request_payload import PatchPaymentIntentRequestPayload


class TestPatchPaymentIntentRequestPayload(unittest.TestCase):
    """PatchPaymentIntentRequestPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchPaymentIntentRequestPayload(self):
        """Test PatchPaymentIntentRequestPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchPaymentIntentRequestPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
