"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.client_secrets_api import ClientSecretsApi  # noqa: E501


class TestClientSecretsApi(unittest.TestCase):
    """ClientSecretsApi unit test stubs"""

    def setUp(self):
        self.api = ClientSecretsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_client_secrets_post(self):
        """Test case for client_secrets_post

        Create a single-use Client Secret  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
