"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.contact import Contact
from openapi_client.model.identity_document_response import IdentityDocumentResponse
globals()['Contact'] = Contact
globals()['IdentityDocumentResponse'] = IdentityDocumentResponse
from openapi_client.model.payer import Payer


class TestPayer(unittest.TestCase):
    """Payer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayer(self):
        """Test Payer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Payer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
