"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_document_upload_request_one_of import CreateDocumentUploadRequestOneOf
from openapi_client.model.create_document_upload_request_one_of1 import CreateDocumentUploadRequestOneOf1
from openapi_client.model.create_document_upload_request_one_of2 import CreateDocumentUploadRequestOneOf2
from openapi_client.model.payer_id import PayerId
from openapi_client.model.payment_id import PaymentId
from openapi_client.model.payment_intent_id import PaymentIntentId
from openapi_client.model.recipient_id import RecipientId
globals()['CreateDocumentUploadRequestOneOf'] = CreateDocumentUploadRequestOneOf
globals()['CreateDocumentUploadRequestOneOf1'] = CreateDocumentUploadRequestOneOf1
globals()['CreateDocumentUploadRequestOneOf2'] = CreateDocumentUploadRequestOneOf2
globals()['PayerId'] = PayerId
globals()['PaymentId'] = PaymentId
globals()['PaymentIntentId'] = PaymentIntentId
globals()['RecipientId'] = RecipientId
from openapi_client.model.create_document_upload_request import CreateDocumentUploadRequest


class TestCreateDocumentUploadRequest(unittest.TestCase):
    """CreateDocumentUploadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDocumentUploadRequest(self):
        """Test CreateDocumentUploadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDocumentUploadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
