"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_method_id import PaymentMethodId


class TestPaymentMethodId(unittest.TestCase):
    """PaymentMethodId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodId(self):
        """Test PaymentMethodId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentMethodId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
