"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payer_id import PayerId
globals()['PayerId'] = PayerId
from openapi_client.model.patch_payment_method_request import PatchPaymentMethodRequest


class TestPatchPaymentMethodRequest(unittest.TestCase):
    """PatchPaymentMethodRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchPaymentMethodRequest(self):
        """Test PatchPaymentMethodRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchPaymentMethodRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
