"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.payments_api import PaymentsApi  # noqa: E501


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payment_intents_id_get(self):
        """Test case for payment_intents_id_get

        Retrieve a single Payment Intent  # noqa: E501
        """
        pass

    def test_payment_intents_id_patch(self):
        """Test case for payment_intents_id_patch

        Update a Payment Intent  # noqa: E501
        """
        pass

    def test_payment_intents_post(self):
        """Test case for payment_intents_post

        Create a Payment Intent  # noqa: E501
        """
        pass

    def test_payments_get(self):
        """Test case for payments_get

        Retrieve a paginated list of payments by query parameter(s)  # noqa: E501
        """
        pass

    def test_payments_id_get(self):
        """Test case for payments_id_get

        Retrieve a single Payment  # noqa: E501
        """
        pass

    def test_payments_id_refunds_post(self):
        """Test case for payments_id_refunds_post

        Refund or cancel an existing Payment  # noqa: E501
        """
        pass

    def test_payments_post(self):
        """Test case for payments_post

        Create a Payment from a Payment Intent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
