"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_refund import PaymentRefund


class TestPaymentRefund(unittest.TestCase):
    """PaymentRefund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentRefund(self):
        """Test PaymentRefund"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentRefund()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
