"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recipient_contact import RecipientContact
globals()['RecipientContact'] = RecipientContact
from openapi_client.model.recipient import Recipient


class TestRecipient(unittest.TestCase):
    """Recipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecipient(self):
        """Test Recipient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Recipient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
