"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recipient_id import RecipientId
globals()['RecipientId'] = RecipientId
from openapi_client.model.create_document_upload_request_one_of2 import CreateDocumentUploadRequestOneOf2


class TestCreateDocumentUploadRequestOneOf2(unittest.TestCase):
    """CreateDocumentUploadRequestOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDocumentUploadRequestOneOf2(self):
        """Test CreateDocumentUploadRequestOneOf2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDocumentUploadRequestOneOf2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
