"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_recipient_request_contact import CreateRecipientRequestContact
from openapi_client.model.payer_id import PayerId
globals()['CreateRecipientRequestContact'] = CreateRecipientRequestContact
globals()['PayerId'] = PayerId
from openapi_client.model.patch_recipient_request import PatchRecipientRequest


class TestPatchRecipientRequest(unittest.TestCase):
    """PatchRecipientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchRecipientRequest(self):
        """Test PatchRecipientRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchRecipientRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
