"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_refund_request import PaymentRefundRequest


class TestPaymentRefundRequest(unittest.TestCase):
    """PaymentRefundRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentRefundRequest(self):
        """Test PaymentRefundRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentRefundRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
