"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.payers_api import PayersApi  # noqa: E501


class TestPayersApi(unittest.TestCase):
    """PayersApi unit test stubs"""

    def setUp(self):
        self.api = PayersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payers_id_delete(self):
        """Test case for payers_id_delete

        Delete a Payer  # noqa: E501
        """
        pass

    def test_payers_id_get(self):
        """Test case for payers_id_get

        Retrieve a Payer  # noqa: E501
        """
        pass

    def test_payers_id_patch(self):
        """Test case for payers_id_patch

        Update a Payer  # noqa: E501
        """
        pass

    def test_payers_post(self):
        """Test case for payers_post

        Create a Payer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
