"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.payment_methods_api import PaymentMethodsApi  # noqa: E501


class TestPaymentMethodsApi(unittest.TestCase):
    """PaymentMethodsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentMethodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payment_methods_get(self):
        """Test case for payment_methods_get

        Retrieve a paginated list of Payment Methods by query parameter(s)  # noqa: E501
        """
        pass

    def test_payment_methods_id_delete(self):
        """Test case for payment_methods_id_delete

        Delete a Payment Method  # noqa: E501
        """
        pass

    def test_payment_methods_id_get(self):
        """Test case for payment_methods_id_get

        Retrieve a Payment Method  # noqa: E501
        """
        pass

    def test_payment_methods_id_patch(self):
        """Test case for payment_methods_id_patch

        Update a Payment Method  # noqa: E501
        """
        pass

    def test_payment_methods_post(self):
        """Test case for payment_methods_post

        Create a Payment Method  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
