"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.amount_details import AmountDetails


class TestAmountDetails(unittest.TestCase):
    """AmountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmountDetails(self):
        """Test AmountDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AmountDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
