"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_payment_intent_request_payload import CreatePaymentIntentRequestPayload
from openapi_client.model.create_payment_request_from_id import CreatePaymentRequestFromId
from openapi_client.model.payment_details import PaymentDetails
globals()['CreatePaymentIntentRequestPayload'] = CreatePaymentIntentRequestPayload
globals()['CreatePaymentRequestFromId'] = CreatePaymentRequestFromId
globals()['PaymentDetails'] = PaymentDetails
from openapi_client.model.create_payment_request import CreatePaymentRequest


class TestCreatePaymentRequest(unittest.TestCase):
    """CreatePaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePaymentRequest(self):
        """Test CreatePaymentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePaymentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
