"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.identity_document_response import IdentityDocumentResponse


class TestIdentityDocumentResponse(unittest.TestCase):
    """IdentityDocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityDocumentResponse(self):
        """Test IdentityDocumentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityDocumentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
