"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.create_document_upload_request import CreateDocumentUploadRequest
from openapi_client.model.document_upload import DocumentUpload
from openapi_client.model.error import Error


class DocumentsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __documents_post(
            self,
            create_document_upload_request,
            **kwargs
        ):
            """Upload a document  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.documents_post(create_document_upload_request, async_req=True)
            >>> result = thread.get()

            Args:
                create_document_upload_request (CreateDocumentUploadRequest): Document metadata

            Keyword Args:
                trace_id (str): A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.. [optional]
                user_agent (str): A string representing the User Agent. Required only when the request is not coming from the end user's browser.. [optional]
                end_user_device_id (str): A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                end_user_ip (str): The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                DocumentUpload
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['create_document_upload_request'] = \
                create_document_upload_request
            return self.call_with_http_info(**kwargs)

        self.documents_post = _Endpoint(
            settings={
                'response_type': (DocumentUpload,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/documents',
                'operation_id': 'documents_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'create_document_upload_request',
                    'trace_id',
                    'user_agent',
                    'end_user_device_id',
                    'end_user_ip',
                ],
                'required': [
                    'create_document_upload_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'create_document_upload_request':
                        (CreateDocumentUploadRequest,),
                    'trace_id':
                        (str,),
                    'user_agent':
                        (str,),
                    'end_user_device_id':
                        (str,),
                    'end_user_ip':
                        (str,),
                },
                'attribute_map': {
                    'trace_id': 'Trace-Id',
                    'user_agent': 'User-Agent',
                    'end_user_device_id': 'End-User-Device-Id',
                    'end_user_ip': 'End-User-Ip',
                },
                'location_map': {
                    'create_document_upload_request': 'body',
                    'trace_id': 'header',
                    'user_agent': 'header',
                    'end_user_device_id': 'header',
                    'end_user_ip': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__documents_post
        )
