"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.create_payment_method_request import CreatePaymentMethodRequest
from openapi_client.model.error import Error
from openapi_client.model.inline_response2003 import InlineResponse2003
from openapi_client.model.patch_payment_method_request import PatchPaymentMethodRequest
from openapi_client.model.payment_method import PaymentMethod


class PaymentMethodsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __payment_methods_get(
            self,
            payer_id,
            **kwargs
        ):
            """Retrieve a paginated list of Payment Methods by query parameter(s)  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_methods_get(payer_id, async_req=True)
            >>> result = thread.get()

            Args:
                payer_id (str): The associated Payer ID to list Payment Methods for

            Keyword Args:
                offset (int): The number of records you wish to skip before selecting records. [optional]
                limit (int): Number of items to return. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                InlineResponse2003
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['payer_id'] = \
                payer_id
            return self.call_with_http_info(**kwargs)

        self.payment_methods_get = _Endpoint(
            settings={
                'response_type': (InlineResponse2003,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-methods',
                'operation_id': 'payment_methods_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'payer_id',
                    'offset',
                    'limit',
                ],
                'required': [
                    'payer_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'payer_id':
                        (str,),
                    'offset':
                        (int,),
                    'limit':
                        (int,),
                },
                'attribute_map': {
                    'payer_id': 'payerId',
                    'offset': 'offset',
                    'limit': 'limit',
                },
                'location_map': {
                    'payer_id': 'query',
                    'offset': 'query',
                    'limit': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__payment_methods_get
        )

        def __payment_methods_id_delete(
            self,
            id,
            **kwargs
        ):
            """Delete a Payment Method  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_methods_id_delete(id, async_req=True)
            >>> result = thread.get()

            Args:
                id (str): The ID of the Payment Method

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['id'] = \
                id
            return self.call_with_http_info(**kwargs)

        self.payment_methods_id_delete = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-methods/{id}',
                'operation_id': 'payment_methods_id_delete',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                ],
                'required': [
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                },
                'location_map': {
                    'id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__payment_methods_id_delete
        )

        def __payment_methods_id_get(
            self,
            payer_id,
            id,
            **kwargs
        ):
            """Retrieve a Payment Method  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_methods_id_get(payer_id, id, async_req=True)
            >>> result = thread.get()

            Args:
                payer_id (str): The Payer ID associated to the Payment Method
                id (str): The ID of the Payment Method

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentMethod
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['payer_id'] = \
                payer_id
            kwargs['id'] = \
                id
            return self.call_with_http_info(**kwargs)

        self.payment_methods_id_get = _Endpoint(
            settings={
                'response_type': (PaymentMethod,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-methods/{id}',
                'operation_id': 'payment_methods_id_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'payer_id',
                    'id',
                ],
                'required': [
                    'payer_id',
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'payer_id':
                        (str,),
                    'id':
                        (str,),
                },
                'attribute_map': {
                    'payer_id': 'payerId',
                    'id': 'id',
                },
                'location_map': {
                    'payer_id': 'query',
                    'id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__payment_methods_id_get
        )

        def __payment_methods_id_patch(
            self,
            id,
            patch_payment_method_request,
            **kwargs
        ):
            """Update a Payment Method  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_methods_id_patch(id, patch_payment_method_request, async_req=True)
            >>> result = thread.get()

            Args:
                id (str): The ID of the Payment Method
                patch_payment_method_request (PatchPaymentMethodRequest): Payment Method to update

            Keyword Args:
                trace_id (str): A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.. [optional]
                user_agent (str): A string representing the User Agent. Required only when the request is not coming from the end user's browser.. [optional]
                end_user_device_id (str): A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                end_user_ip (str): The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentMethod
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['id'] = \
                id
            kwargs['patch_payment_method_request'] = \
                patch_payment_method_request
            return self.call_with_http_info(**kwargs)

        self.payment_methods_id_patch = _Endpoint(
            settings={
                'response_type': (PaymentMethod,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-methods/{id}',
                'operation_id': 'payment_methods_id_patch',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'patch_payment_method_request',
                    'trace_id',
                    'user_agent',
                    'end_user_device_id',
                    'end_user_ip',
                ],
                'required': [
                    'id',
                    'patch_payment_method_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'patch_payment_method_request':
                        (PatchPaymentMethodRequest,),
                    'trace_id':
                        (str,),
                    'user_agent':
                        (str,),
                    'end_user_device_id':
                        (str,),
                    'end_user_ip':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                    'trace_id': 'Trace-Id',
                    'user_agent': 'User-Agent',
                    'end_user_device_id': 'End-User-Device-Id',
                    'end_user_ip': 'End-User-Ip',
                },
                'location_map': {
                    'id': 'path',
                    'patch_payment_method_request': 'body',
                    'trace_id': 'header',
                    'user_agent': 'header',
                    'end_user_device_id': 'header',
                    'end_user_ip': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__payment_methods_id_patch
        )

        def __payment_methods_post(
            self,
            create_payment_method_request,
            **kwargs
        ):
            """Create a Payment Method  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_methods_post(create_payment_method_request, async_req=True)
            >>> result = thread.get()

            Args:
                create_payment_method_request (CreatePaymentMethodRequest): Payment Method to create

            Keyword Args:
                trace_id (str): A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.. [optional]
                user_agent (str): A string representing the User Agent. Required only when the request is not coming from the end user's browser.. [optional]
                end_user_device_id (str): A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                end_user_ip (str): The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentMethod
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['create_payment_method_request'] = \
                create_payment_method_request
            return self.call_with_http_info(**kwargs)

        self.payment_methods_post = _Endpoint(
            settings={
                'response_type': (PaymentMethod,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-methods',
                'operation_id': 'payment_methods_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'create_payment_method_request',
                    'trace_id',
                    'user_agent',
                    'end_user_device_id',
                    'end_user_ip',
                ],
                'required': [
                    'create_payment_method_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'create_payment_method_request':
                        (CreatePaymentMethodRequest,),
                    'trace_id':
                        (str,),
                    'user_agent':
                        (str,),
                    'end_user_device_id':
                        (str,),
                    'end_user_ip':
                        (str,),
                },
                'attribute_map': {
                    'trace_id': 'Trace-Id',
                    'user_agent': 'User-Agent',
                    'end_user_device_id': 'End-User-Device-Id',
                    'end_user_ip': 'End-User-Ip',
                },
                'location_map': {
                    'create_payment_method_request': 'body',
                    'trace_id': 'header',
                    'user_agent': 'header',
                    'end_user_device_id': 'header',
                    'end_user_ip': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__payment_methods_post
        )
