"""
    Plastiq Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.create_payment_intent_request_payload import CreatePaymentIntentRequestPayload
from openapi_client.model.create_payment_request import CreatePaymentRequest
from openapi_client.model.error import Error
from openapi_client.model.inline_response2002 import InlineResponse2002
from openapi_client.model.patch_payment_intent_request_payload import PatchPaymentIntentRequestPayload
from openapi_client.model.payment import Payment
from openapi_client.model.payment_intent import PaymentIntent
from openapi_client.model.payment_refund import PaymentRefund
from openapi_client.model.payment_refund_request import PaymentRefundRequest


class PaymentsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __payment_intents_id_get(
            self,
            payer_id,
            id,
            **kwargs
        ):
            """Retrieve a single Payment Intent  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_intents_id_get(payer_id, id, async_req=True)
            >>> result = thread.get()

            Args:
                payer_id (str): The Payer ID of the Payment Intent
                id (str): The ID of the Payment Intent

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentIntent
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['payer_id'] = \
                payer_id
            kwargs['id'] = \
                id
            return self.call_with_http_info(**kwargs)

        self.payment_intents_id_get = _Endpoint(
            settings={
                'response_type': (PaymentIntent,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-intents/{id}',
                'operation_id': 'payment_intents_id_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'payer_id',
                    'id',
                ],
                'required': [
                    'payer_id',
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'payer_id':
                        (str,),
                    'id':
                        (str,),
                },
                'attribute_map': {
                    'payer_id': 'payerId',
                    'id': 'id',
                },
                'location_map': {
                    'payer_id': 'query',
                    'id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__payment_intents_id_get
        )

        def __payment_intents_id_patch(
            self,
            id,
            patch_payment_intent_request_payload,
            **kwargs
        ):
            """Update a Payment Intent  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_intents_id_patch(id, patch_payment_intent_request_payload, async_req=True)
            >>> result = thread.get()

            Args:
                id (str): The ID of the Payment Intent
                patch_payment_intent_request_payload (PatchPaymentIntentRequestPayload): Payment Intent to update

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentIntent
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['id'] = \
                id
            kwargs['patch_payment_intent_request_payload'] = \
                patch_payment_intent_request_payload
            return self.call_with_http_info(**kwargs)

        self.payment_intents_id_patch = _Endpoint(
            settings={
                'response_type': (PaymentIntent,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-intents/{id}',
                'operation_id': 'payment_intents_id_patch',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'patch_payment_intent_request_payload',
                ],
                'required': [
                    'id',
                    'patch_payment_intent_request_payload',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'patch_payment_intent_request_payload':
                        (PatchPaymentIntentRequestPayload,),
                },
                'attribute_map': {
                    'id': 'id',
                },
                'location_map': {
                    'id': 'path',
                    'patch_payment_intent_request_payload': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__payment_intents_id_patch
        )

        def __payment_intents_post(
            self,
            create_payment_intent_request_payload,
            **kwargs
        ):
            """Create a Payment Intent  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payment_intents_post(create_payment_intent_request_payload, async_req=True)
            >>> result = thread.get()

            Args:
                create_payment_intent_request_payload (CreatePaymentIntentRequestPayload): Create a Payment Intent object staging it for execution

            Keyword Args:
                trace_id (str): A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.. [optional]
                user_agent (str): A string representing the User Agent. Required only when the request is not coming from the end user's browser.. [optional]
                end_user_device_id (str): A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                end_user_ip (str): The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentIntent
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['create_payment_intent_request_payload'] = \
                create_payment_intent_request_payload
            return self.call_with_http_info(**kwargs)

        self.payment_intents_post = _Endpoint(
            settings={
                'response_type': (PaymentIntent,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payment-intents',
                'operation_id': 'payment_intents_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'create_payment_intent_request_payload',
                    'trace_id',
                    'user_agent',
                    'end_user_device_id',
                    'end_user_ip',
                ],
                'required': [
                    'create_payment_intent_request_payload',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'create_payment_intent_request_payload':
                        (CreatePaymentIntentRequestPayload,),
                    'trace_id':
                        (str,),
                    'user_agent':
                        (str,),
                    'end_user_device_id':
                        (str,),
                    'end_user_ip':
                        (str,),
                },
                'attribute_map': {
                    'trace_id': 'Trace-Id',
                    'user_agent': 'User-Agent',
                    'end_user_device_id': 'End-User-Device-Id',
                    'end_user_ip': 'End-User-Ip',
                },
                'location_map': {
                    'create_payment_intent_request_payload': 'body',
                    'trace_id': 'header',
                    'user_agent': 'header',
                    'end_user_device_id': 'header',
                    'end_user_ip': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__payment_intents_post
        )

        def __payments_get(
            self,
            payer_id,
            **kwargs
        ):
            """Retrieve a paginated list of payments by query parameter(s)  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payments_get(payer_id, async_req=True)
            >>> result = thread.get()

            Args:
                payer_id (str): The associated Payer ID to list payments for

            Keyword Args:
                offset (int): The number of records you wish to skip before selecting records. [optional]
                limit (int): Number of items to return. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                InlineResponse2002
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['payer_id'] = \
                payer_id
            return self.call_with_http_info(**kwargs)

        self.payments_get = _Endpoint(
            settings={
                'response_type': (InlineResponse2002,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payments',
                'operation_id': 'payments_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'payer_id',
                    'offset',
                    'limit',
                ],
                'required': [
                    'payer_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'payer_id':
                        (str,),
                    'offset':
                        (int,),
                    'limit':
                        (int,),
                },
                'attribute_map': {
                    'payer_id': 'payerId',
                    'offset': 'offset',
                    'limit': 'limit',
                },
                'location_map': {
                    'payer_id': 'query',
                    'offset': 'query',
                    'limit': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__payments_get
        )

        def __payments_id_get(
            self,
            payer_id,
            id,
            **kwargs
        ):
            """Retrieve a single Payment  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payments_id_get(payer_id, id, async_req=True)
            >>> result = thread.get()

            Args:
                payer_id (str): The Payer ID associated with the Payment
                id (str): The ID of the Payment

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Payment
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['payer_id'] = \
                payer_id
            kwargs['id'] = \
                id
            return self.call_with_http_info(**kwargs)

        self.payments_id_get = _Endpoint(
            settings={
                'response_type': (Payment,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payments/{id}',
                'operation_id': 'payments_id_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'payer_id',
                    'id',
                ],
                'required': [
                    'payer_id',
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'payer_id':
                        (str,),
                    'id':
                        (str,),
                },
                'attribute_map': {
                    'payer_id': 'payerId',
                    'id': 'id',
                },
                'location_map': {
                    'payer_id': 'query',
                    'id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__payments_id_get
        )

        def __payments_id_refunds_post(
            self,
            id,
            payment_refund_request,
            **kwargs
        ):
            """Refund or cancel an existing Payment  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payments_id_refunds_post(id, payment_refund_request, async_req=True)
            >>> result = thread.get()

            Args:
                id (str): The ID of the Payment to refund
                payment_refund_request (PaymentRefundRequest): Payment Refund body

            Keyword Args:
                trace_id (str): A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaymentRefund
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['id'] = \
                id
            kwargs['payment_refund_request'] = \
                payment_refund_request
            return self.call_with_http_info(**kwargs)

        self.payments_id_refunds_post = _Endpoint(
            settings={
                'response_type': (PaymentRefund,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payments/{id}/refunds',
                'operation_id': 'payments_id_refunds_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'payment_refund_request',
                    'trace_id',
                ],
                'required': [
                    'id',
                    'payment_refund_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'payment_refund_request':
                        (PaymentRefundRequest,),
                    'trace_id':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                    'trace_id': 'Trace-Id',
                },
                'location_map': {
                    'id': 'path',
                    'payment_refund_request': 'body',
                    'trace_id': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__payments_id_refunds_post
        )

        def __payments_post(
            self,
            create_payment_request,
            **kwargs
        ):
            """Create a Payment from a Payment Intent  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.payments_post(create_payment_request, async_req=True)
            >>> result = thread.get()

            Args:
                create_payment_request (CreatePaymentRequest): Payment to create

            Keyword Args:
                trace_id (str): A valid UUID (V4) for tracing requests. Will be returned as a header. If not present or invalid, a generated UUID will be returned.. [optional]
                user_agent (str): A string representing the User Agent. Required only when the request is not coming from the end user's browser.. [optional]
                end_user_device_id (str): A unique identifier for the end user's browser. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                end_user_ip (str): The IP address of the end user. Recommended for compliance when the request is not coming from the end user's browser.. [optional]
                idempotency_key (str): A valid UUID (V4) for handling duplicate requests. Will return original status code, response body, and set a 'Idempotent-Replay' header on response for a given key if a match exists.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Payment
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['create_payment_request'] = \
                create_payment_request
            return self.call_with_http_info(**kwargs)

        self.payments_post = _Endpoint(
            settings={
                'response_type': (Payment,),
                'auth': [
                    'BearerAuth'
                ],
                'endpoint_path': '/payments',
                'operation_id': 'payments_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'create_payment_request',
                    'trace_id',
                    'user_agent',
                    'end_user_device_id',
                    'end_user_ip',
                    'idempotency_key',
                ],
                'required': [
                    'create_payment_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'create_payment_request':
                        (CreatePaymentRequest,),
                    'trace_id':
                        (str,),
                    'user_agent':
                        (str,),
                    'end_user_device_id':
                        (str,),
                    'end_user_ip':
                        (str,),
                    'idempotency_key':
                        (str,),
                },
                'attribute_map': {
                    'trace_id': 'Trace-Id',
                    'user_agent': 'User-Agent',
                    'end_user_device_id': 'End-User-Device-Id',
                    'end_user_ip': 'End-User-Ip',
                    'idempotency_key': 'Idempotency-Key',
                },
                'location_map': {
                    'create_payment_request': 'body',
                    'trace_id': 'header',
                    'user_agent': 'header',
                    'end_user_device_id': 'header',
                    'end_user_ip': 'header',
                    'idempotency_key': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__payments_post
        )
